import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { dir } from "i18next";
import { SelectLang } from "@/components/ui/select-lang";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  return (
    <html lang={lang} dir={dir(lang)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <SelectLang />
        </nav>
        <main className="flex flex-col items-center justify-center h-screen">
          {children}
        </main>
        <footer className="mx-auto w-full">
          <small className="text-xs text-gray-500 text-center w-full inline-block">
            © 2025 Yorokobi All rights reserved. | Made by{" "}
            <a
              href="https://x.com/seventhseven"
              target="_blank"
              rel="noopener noreferrer"
            >
              Shumpei
            </a>
          </small>
        </footer>
      </body>
    </html>
  );
}
